// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// SVM
Rcpp:: List SVM(const arma::vec& y, const arma::uword nloop, const arma::uword burnin, const arma::uword skip);
RcppExport SEXP _SVs_SVM(SEXP ySEXP, SEXP nloopSEXP, SEXP burninSEXP, SEXP skipSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type nloop(nloopSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type skip(skipSEXP);
    rcpp_result_gen = Rcpp::wrap(SVM(y, nloop, burnin, skip));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SVs_SVM", (DL_FUNC) &_SVs_SVM, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_SVs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
